server.port: 8088

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

jwt-secret-key: ${JWT_SECRET_KEY}
user-microservice: ${USER_MICROSERVICE}
post-microservice: ${POST_MICROSERVICE}